# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appName: redis
appImage: redis
appVersion: alpine
appReplicas: 1
containerPort: 6379
volumeName: redis-data
containerMountPath: /data

servicePort: 6379